server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qzhou_hotel?useSSL=false
    username: root
    password: zhouq
    driver-class-name: com.mysql.jdbc.Driver

logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
  level:
    com.qzhou: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.qzhou.hotel.pojo