logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    addresses: 43.143.200.250
    username: qzhou
    password: 123
    virtual-host: /
    port: 5672
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息